apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: argo-web
  name: argo-web
  namespace: web-app
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 80
  selector:
    app: argo-web
  type: ClusterIP
status:
  loadBalancer: {}
