apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argo-web
  name: argo-web
  namespace: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo-web
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
